// <auto-generated />
using MVC_TV_Shop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_TV_Shop.Migrations
{
    [DbContext(typeof(TvShopDbContext))]
    partial class TvShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MVC_TV_Shop.Models.TVModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Diagonal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TVs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Diagonal = "55″",
                            Model = "Samsung QE55QN90BAUXUA Neo",
                            Price = 73999m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 2,
                            Diagonal = "65″",
                            Model = "Samsung QE65Q70BAUXUA",
                            Price = 62999m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 3,
                            Diagonal = "65″",
                            Model = "Samsung QE65Q60BAUXUA",
                            Price = 52199m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 4,
                            Diagonal = "55″",
                            Model = "Samsung UE55BU8500UXUA",
                            Price = 28399m,
                            Year = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
